In [1]:
import numpy as np


# 1. 1D, 2D, 3D arrays

In [3]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2], [3, 4]])
a3 = np.array([[[1], [2]], [[3], [4]]])


In [10]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[[1],
         [2]],
 
        [[3],
         [4]]]))

# 2. Arrays of zeros, ones, fives


In [11]:

zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)
zeros, ones, fives

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

# 3. Integers from 10 to 50


In [12]:
arr_10_50 = np.arange(10, 51)
arr_10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 4. 20 evenly spaced values from 1 to 10


In [13]:
even_20 = np.linspace(1, 10, 20)
even_20

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# 5. 3x3 Identity matrix


In [15]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 6. 5x5 matrix from 1 to 25


In [17]:
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
matrix_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 7. Shape, size, dtype of array

In [19]:
print("Shape:", matrix_5x5.shape)
print("Size:", matrix_5x5.size)
print("Dtype:", matrix_5x5.dtype)


Shape: (5, 5)
Size: 25
Dtype: int64


# 8. Access 3rd row, 2nd column


In [21]:

arr = np.arange(1, 26).reshape(5, 5)



In [26]:
val = arr[2, 1]  # row index 2, column index 1
val


np.int64(12)

# 9. Reverse array


In [29]:
row_reversed = arr[::-1]
col_reversed = arr[:, ::-1]
row_reversed, col_reversed

(array([[21, 22, 23, 24, 25],
        [16, 17, 18, 19, 20],
        [11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5]]),
 array([[ 5,  4,  3,  2,  1],
        [10,  9,  8,  7,  6],
        [15, 14, 13, 12, 11],
        [20, 19, 18, 17, 16],
        [25, 24, 23, 22, 21]]))

# 10. Select every second elemen

In [31]:
arr1d = np.array([10, 20, 30, 40, 50, 60])
arr1d[::2]


array([10, 30, 50])

# 11. Change value at specific index

In [32]:
arr1d[2] = 99
arr1d

array([10, 20, 99, 40, 50, 60])

# 12. Extract submatrix

In [33]:
submatrix = arr[0:2, 0:2]
submatrix


array([[1, 2],
       [6, 7]])

In [34]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])



# 13. Add, subtract, multiply, divide


In [35]:
a+b

array([11, 22, 33])

In [36]:
a-b

array([ 9, 18, 27])

In [37]:
a*b

array([10, 40, 90])

In [38]:
a/b

array([10., 10., 10.])

# 14. Square every element


In [39]:
a ** 2

array([100, 400, 900])

# 15. Max, Min, Mean


In [42]:
a.min()


np.int64(10)

In [43]:
a.max()

np.int64(30)

In [44]:
a.mean()

np.float64(20.0)

# 16. Standard Deviation


In [45]:
a.std()

np.float64(8.16496580927726)

# 17. Sort


In [53]:
unsorted = np.array([3, 1, 4, 2])


In [54]:
np.sort(unsorted)



array([1, 2, 3, 4])

# 18. Clip values between 5 and 25


In [55]:
np.clip(a, 5, 25)


array([10, 20, 25])

# ..

In [59]:
arr = np.array([10, 55, 23, 78, 0, 3, 66, 91])


# 19. Get all elements > 50


In [61]:
greater_than_50 = arr[arr > 50]
greater_than_50


array([55, 78, 66, 91])

# 20. Replace all odd numbers with -1


In [62]:
arr_odd_replaced = np.copy(arr)
arr_odd_replaced[arr_odd_replaced % 2 != 0] = -1
arr_odd_replaced



array([10, -1, -1, 78,  0, -1, 66, -1])

# 21. Count elements divisible by 3



In [73]:
count_div_3 = np.sum(arr % 3 == 0)
count_div_3



np.int64(4)

# 22. Indices of non-zero elements



In [74]:
indices_nonzero = np.nonzero(arr)
indices_nonzero[0]


array([0, 1, 2, 3, 5, 6, 7])

# 23. Create a random 3x3 matrix


In [75]:
random_matrix = np.random.rand(3, 3)
random_matrix


array([[0.94806212, 0.91239655, 0.63135638],
       [0.63133527, 0.85288568, 0.26719638],
       [0.5681907 , 0.19229435, 0.25434146]])

# 24. Transpose a matrix


transposed = random_matrix.T
transposed

# 25. Multiply two matrices (dot product)


In [77]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)
dot_product


array([[19, 22],
       [43, 50]])

# 26. Check if two arrays are equal


In [78]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
are_equal = np.array_equal(array1, array2)
are_equal


True

# 27. Flatten a 2D array to 1D


In [82]:
flat_array = matrix_a.flatten()
flat_array

array([1, 2, 3, 4])

# 28. Generate random numbers


In [84]:
rand_float = np.random.rand(5)
rand_float

array([0.04049196, 0.79824901, 0.98244635, 0.23070988, 0.41676488])

In [86]:
rand_int = np.random.randint(1, 10, 5)  

rand_int


array([3, 9, 4, 7, 1])

# 29. Set seed for reproducibilit

In [87]:
np.random.seed(42)
seeded_rand = np.random.rand(3)
seeded_rand

array([0.37454012, 0.95071431, 0.73199394])

# 30. Find unique elements in an array


In [89]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
unique_elements

array([1, 2, 3, 4, 5])